language: node_js
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
branches:
  only:
    - main
node_js:
  - 'node'
script:
  - yarn lint
after_success:
  - docker build . -t scartech70/armory-ui
  - docker push scartech70/armory-ui
